#ifndef RPIBM_BCM2837B0_H
#define RPIBM_BCM2837B0_H

#define SYSTEM_CLK_FREQ 250000000U // set in config.txt

#define RPIBM_PERIPH_BASE_ADDR 0x3F000000

/* GPIO */
#define RPIBM_GPIO_OFFSET         0x200000
#define RPIBM_GPIO_GPFSEL0_OFFSET 0x0
#define RPIBM_GPIO_GPFSEL1_OFFSET 0x4
#define RPIBM_GPIO_GPFSEL2_OFFSET 0x8
#define RPIBM_GPIO_GPFSEL3_OFFSET 0xC
#define RPIBM_GPIO_GPFSEL4_OFFSET 0x10
#define RPIBM_GPIO_GPFSEL5_OFFSET 0x14

#define RPIBM_GPIO_GPSET0_OFFSET 0x1C
#define RPIBM_GPIO_GPSET1_OFFSET 0x20

#define RPIBM_GPIO_GPCLR0_OFFSET 0x28
#define RPIBM_GPIO_GPCLR1_OFFSET 0x2C

#define RPIBM_GPIO_BASE_ADDR    (RPIBM_PERIPH_BASE_ADDR + RPIBM_GPIO_OFFSET)
#define RPIBM_GPIO_GPFSEL0_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL0_OFFSET)
#define RPIBM_GPIO_GPFSEL1_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL1_OFFSET)
#define RPIBM_GPIO_GPFSEL2_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL2_OFFSET)
#define RPIBM_GPIO_GPFSEL3_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL3_OFFSET)
#define RPIBM_GPIO_GPFSEL4_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL4_OFFSET)
#define RPIBM_GPIO_GPFSEL5_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL5_OFFSET)
#define RPIBM_GPIO_GPSET0_ADDR  (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPSET0_OFFSET)
#define RPIBM_GPIO_GPSET1_ADDR  (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPSET1_OFFSET)
#define RPIBM_GPIO_GPCLR0_ADDR  (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPCLR0_OFFSET)
#define RPIBM_GPIO_GPCLR1_ADDR  (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPCLR1_OFFSET)

/* System Timer*/
#define RPIBM_TIMER_OFFSET     0x3000
#define RPIBM_TIMER_CS_OFFSET  0x0
#define RPIBM_TIMER_CLO_OFFSET 0x4
#define RPIBM_TIMER_CHI_OFFSET 0x8
#define RPIBM_TIMER_C0_OFFSET  0xC
#define RPIBM_TIMER_C1_OFFSET  0x10
#define RPIBM_TIMER_C2_OFFSET  0x14
#define RPIBM_TIMER_C3_OFFSET  0x18

#define RPIBM_TIMER_BASE_ADDR (RPIBM_PERIPH_BASE_ADDR + RPIBM_TIMER_OFFSET)
#define RPIBM_TIMER_CS_ADDR   (RPIBM_TIMER_BASE_ADDR + RPIBM_TIMER_CS_OFFSET)
#define RPIBM_TIMER_CLO_ADDR  (RPIBM_TIMER_BASE_ADDR + RPIBM_TIMER_CLO_OFFSET)
#define RPIBM_TIMER_CHI_ADDR  (RPIBM_TIMER_BASE_ADDR + RPIBM_TIMER_CHI_OFFSET)
#define RPIBM_TIMER_C0_ADDR   (RPIBM_TIMER_BASE_ADDR + RPIBM_TIMER_C0_OFFSET)
#define RPIBM_TIMER_C1_ADDR   (RPIBM_TIMER_BASE_ADDR + RPIBM_TIMER_C1_OFFSET)
#define RPIBM_TIMER_C2_ADDR   (RPIBM_TIMER_BASE_ADDR + RPIBM_TIMER_C2_OFFSET)
#define RPIBM_TIMER_C3_ADDR   (RPIBM_TIMER_BASE_ADDR + RPIBM_TIMER_C3_OFFSET)

/* AUX Registers*/
#define RPIBM_AUX_OFFSET         0x215000
#define RPIBM_AUX_ENABLES_OFFSET 0x4

#define RPIBM_AUX_BASE_ADDR    (RPIBM_PERIPH_BASE_ADDR + RPIBM_AUX_OFFSET)
#define RPIBM_AUX_ENABLES_ADDR (RPIBM_AUX_BASE_ADDR + RPIBM_AUX_ENABLES_OFFSET)

/* Mini UART */
#define RPIBM_MINI_UART_IO_OFFSET      0x40
#define RPIBM_MINI_UART_IER_OFFSET     0x44
#define RPIBM_MINI_UART_IIR_OFFSET     0x48
#define RPIBM_MINI_UART_LCR_OFFSET     0x4C
#define RPIBM_MINI_UART_MCR_OFFSET     0x50
#define RPIBM_MINI_UART_LSR_OFFSET     0x54
#define RPIBM_MINI_UART_MSR_OFFSET     0x58
#define RPIBM_MINI_UART_SCRATCH_OFFSET 0x5C
#define RPIBM_MINI_UART_CNTL_OFFSET    0x60
#define RPIBM_MINI_UART_STAT_OFFSET    0x64
#define RPIBM_MINI_UART_BAUD_OFFSET    0x68

#define RPIBM_MINI_UART_BASE_ADDR    (RPIBM_AUX_BASE_ADDR)
#define RPIBM_MINI_UART_IO_ADDR      (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_IO_OFFSET)
#define RPIBM_MINI_UART_IER_ADDR     (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_IER_OFFSET)
#define RPIBM_MINI_UART_IIR_ADDR     (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_IIR_OFFSET)
#define RPIBM_MINI_UART_LCR_ADDR     (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_LCR_OFFSET)
#define RPIBM_MINI_UART_MCR_ADDR     (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_MCR_OFFSET)
#define RPIBM_MINI_UART_LSR_ADDR     (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_LSR_OFFSET)
#define RPIBM_MINI_UART_MSR_ADDR     (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_MSR_OFFSET)
#define RPIBM_MINI_UART_SCRATCH_ADDR (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_SCRATCH_OFFSET)
#define RPIBM_MINI_UART_CNTL_ADDR    (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_CNTL_OFFSET)
#define RPIBM_MINI_UART_STAT_ADDR    (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_STAT_OFFSET)
#define RPIBM_MINI_UART_BAUD_ADDR    (RPIBM_MINI_UART_BASE_ADDR + RPIBM_MINI_UART_BAUD_OFFSET)

/* Interrupts */
#define RPIBM_IRQ_OFFSET               0xB000
#define RPIBM_IRQ_BASIC_PENDING_OFFSET 0x200
#define RPIBM_IRQ_PENDING1_OFFSET      0x204
#define RPIBM_IRQ_PENDING2_OFFSET      0x208
#define RPIBM_IRQ_FIQ_CTL_OFFSET       0x20C
#define RPIBM_IRQ_ENABLE1_OFFSET       0x210
#define RPIBM_IRQ_ENABLE2_OFFSET       0x214
#define RPIBM_IRQ_ENABLE_BASIC_OFFSET  0x218
#define RPIBM_IRQ_DISABLE1_OFFSET      0x21C
#define RPIBM_IRQ_DISABLE2_OFFSET      0x220
#define RPIBM_IRQ_DISABLE_BASIC_OFFSET 0x224

#define RPIBM_IRQ_BASE_ADDR          (RPIBM_PERIPH_BASE_ADDR + RPIBM_IRQ_OFFSET)
#define RPIBM_IRQ_BASIC_PENDING_ADDR (RPIBM_IRQ_BASE_ADDR + RPIBM_IRQ_BASIC_PENDING_OFFSET)
#define RPIBM_IRQ_PENDING1_ADDR      (RPIBM_IRQ_BASE_ADDR + RPIBM_IRQ_PENDING1_OFFSET)
#define RPIBM_IRQ_PENDING2_ADDR      (RPIBM_IRQ_BASE_ADDR + RPIBM_IRQ_PENDING2_OFFSET)
#define RPIBM_IRQ_FIQ_CTL_ADDR       (RPIBM_IRQ_BASE_ADDR + RPIBM_IRQ_FIQ_CTL_OFFSET)
#define RPIBM_IRQ_ENABLE1_ADDR       (RPIBM_IRQ_BASE_ADDR + RPIBM_IRQ_ENABLE1_OFFSET)
#define RPIBM_IRQ_ENABLE2_ADDR       (RPIBM_IRQ_BASE_ADDR + RPIBM_IRQ_ENABLE2_OFFSET)
#define RPIBM_IRQ_ENABLE_BASIC_ADDR  (RPIBM_IRQ_BASE_ADDR + RPIBM_IRQ_ENABLE_BASIC_OFFSET)
#define RPIBM_IRQ_DISABLE1_ADDR      (RPIBM_IRQ_BASE_ADDR + RPIBM_IRQ_DISABLE1_OFFSET)
#define RPIBM_IRQ_DISABLE2_ADDR      (RPIBM_IRQ_BASE_ADDR + RPIBM_IRQ_DISABLE2_OFFSET)
#define RPIBM_IRQ_DISABLE_BASIC_ADDR (RPIBM_IRQ_BASE_ADDR + RPIBM_IRQ_DISABLE_BASIC_OFFSET)
#endif // RPIBM_BCM2837B0_H