#ifndef RPIBM_BCM2837B0_H
#define RPIBM_BCM2837B0_H

#define RPIBM_PERIPH_BASE_ADDR 0x3F000000

#define RPIBM_GPIO_OFFSET         0x00200000
#define RPIBM_GPIO_GPFSEL0_OFFSET 0x00
#define RPIBM_GPIO_GPFSEL1_OFFSET 0x04
#define RPIBM_GPIO_GPFSEL2_OFFSET 0x08
#define RPIBM_GPIO_GPFSEL3_OFFSET 0x0C
#define RPIBM_GPIO_GPFSEL4_OFFSET 0x10
#define RPIBM_GPIO_GPFSEL5_OFFSET 0x14

#define RPIBM_GPIO_GPSET0_OFFSET 0x1C
#define RPIBM_GPIO_GPSET1_OFFSET 0x20

#define RPIBM_GPIO_GPCLR0_OFFSET 0x28
#define RPIBM_GPIO_GPCLR1_OFFSET 0x2C

#define RPIBM_GPIO_BASE_ADDR    (RPIBM_PERIPH_BASE_ADDR + RPIBM_GPIO_OFFSET)
#define RPIBM_GPIO_GPFSEL0_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL0_OFFSET)
#define RPIBM_GPIO_GPFSEL1_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL1_OFFSET)
#define RPIBM_GPIO_GPFSEL2_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL2_OFFSET)
#define RPIBM_GPIO_GPFSEL3_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL3_OFFSET)
#define RPIBM_GPIO_GPFSEL4_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL4_OFFSET)
#define RPIBM_GPIO_GPFSEL5_ADDR (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPFSEL5_OFFSET)
#define RPIBM_GPIO_GPSET0_ADDR  (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPSET0_OFFSET)
#define RPIBM_GPIO_GPSET1_ADDR  (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPSET1_OFFSET)
#define RPIBM_GPIO_GPCLR0_ADDR  (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPCLR0_OFFSET)
#define RPIBM_GPIO_GPCLR1_ADDR  (RPIBM_GPIO_BASE_ADDR + RPIBM_GPIO_GPCLR1_OFFSET)

#endif // RPIBM_BCM2837B0_H